AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - com::dealine_notification
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  Dealine_notificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
  TasksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TasksTable
      AttributeDefinitions:
        - AttributeName: taskId
          AttributeType: S
      KeySchema:
        - AttributeName: taskId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: false
      Tags:
        - Key: Environment
          Value: Production

    CreateDeadlineEventLambda:
      Type: AWS::Serverless::Function
      Properties:
        Handler: com.example.CreateDeadlineEvent::handleRequest
        Runtime: java17
        CodeUri: ./src
        MemorySize: 512
        Timeout: 30
        Policies:
          - DynamoDBReadPolicy:
              TableName: !Ref TasksTable
          - Statement:
              - Effect: Allow
                Action:
                  - dynamodb:DescribeStream
                  - dynamodb:GetRecords
                  - dynamodb:GetShardIterator
                  - dynamodb:ListStreams
                Resource: !GetAtt TasksTable.StreamArn
        Events:
          DynamoStream:
            Type: DynamoDB
            Properties:
              Stream: !GetAtt TasksTable.StreamArn
              StartingPosition: LATEST
              BatchSize: 10
              Enabled: true
Outputs:
  Dealine_notificationApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: Dealine_notificationApi
